[profile.default]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
verbosity = 3

[profile.lite]
optimizer = false

[fmt]
line_length = 140
number_underscore = "thousands"
wrap_comments = true

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }
